// ─────────────────────────────────────────────────────────────
// Screen Configuration — Role-Separated Exports
// Each array contains only the screens accessible to that role.
// ─────────────────────────────────────────────────────────────

// ── Citizen Portal Screens ──────────────────────────────────
export const citizenScreens = [
  {
    id: "dashboard",
    path: "dashboard",
    title: "Dashboard",
    icon: "dashboard",
    filename: "2b2e31a552f347ffb338c830cd101922_SafeNet AI _ Citizen Dashboard.html",
    description: "Personal portal for citizens to view alerts, file reports, and track investigation updates.",
    section: "Overview",
  },
  {
    id: "fraud-shield",
    path: "fraud-shield",
    title: "AI Fraud Shield",
    icon: "shield_person",
    filename: "3bd34a1afb614ee1855614a2ad682fa1_SafeNet AI _ Citizen Fraud Shield.html",
    description: "AI assistant interface for citizens to verify suspicious links, numbers, and report threats.",
    section: "Tools",
  },
  {
    id: "currency-detector",
    path: "currency-detector",
    title: "Currency Detector",
    icon: "payments",
    filename: "24ba6e2d102649269f47ee4a6c4b427f_SafeNet AI _ Currency Detector.html",
    description: "Computer vision toolkit to verify bank note denominations, watermarks, and security threads.",
    section: "Tools",
  },
  {
    id: "scam-call-analyzer",
    path: "scam-call-analyzer",
    title: "Scam Call Analyzer",
    icon: "settings_phone",
    filename: "15c313655a704125bcc4528018789510_SafeNet AI _ Scam Call Analyzer.html",
    description: "Interactive voice and transcript analysis to verify call legitimacy and detect caller spoofing.",
    section: "Tools",
  },
  {
    id: "my-complaints",
    path: "my-complaints",
    title: "My Complaints",
    icon: "assignment_late",
    filename: "19115426d87249b5a10beba438504720_SafeNet AI _ My Complaints.html",
    description: "Filing and tracking platform for fraud complaints submitted by citizens to law enforcement.",
    section: "My Activity",
  },
  {
    id: "awareness-center",
    path: "awareness-center",
    title: "Awareness Center",
    icon: "campaign",
    filename: "0b775d6a3d5846319b67a1d1e99bd3da_SafeNet AI _ Awareness Center.html",
    description: "Public hub featuring security advisories, scam alert live feed, and educational resources.",
    section: "Resources",
  },
];

// ── Officer / Law Enforcement Portal Screens ────────────────
export const officerScreens = [
  {
    id: "dashboard",
    path: "dashboard",
    title: "Command Center",
    icon: "admin_panel_settings",
    filename: "80abb45a24d14286bc80647e693b5b01_SafeNet AI _ Command Center.html",
    description: "Active threat room interface displaying real-time incidents, alerts, and dispatch controls.",
    section: "Operations",
  },
  {
    id: "officer-management",
    path: "officers",
    title: "Officer Management",
    icon: "badge",
    filename: "4a1666b2ac774037a262412fa33c515c_SafeNet AI _ Officer Management.html",
    description: "Directory and assignment dashboard to coordinate cyber crime officers and response units.",
    section: "Operations",
  },
  {
    id: "investigation-reports",
    path: "reports",
    title: "Investigation Reports",
    icon: "description",
    filename: "39dfcaaf71e94d7ebafe842dbf682ef2_SafeNet AI _ Investigation Reports.html",
    description: "Case file system containing transcripts, AI summaries, and evidence for active prosecutions.",
    section: "Operations",
  },
  {
    id: "evidence-management",
    path: "evidence",
    title: "Evidence Management",
    icon: "folder_zip",
    filename: "34c71ad8b7df4169b2bb223860d7178c_SafeNet AI _ Evidence Management.html",
    description: "Secure archive storing digital forensic details, transaction hashes, and metadata.",
    section: "Operations",
  },
  {
    id: "crime-heatmap",
    path: "heatmap",
    title: "Crime Heatmap",
    icon: "map",
    filename: "186710cf74d44c628ee9dda4c6ef7f28_SafeNet AI _ Crime Heatmap Intelligence.html",
    description: "Geospatial visualization of cyber incidents, victim distribution, and hot spot trends.",
    section: "Intelligence",
  },
  {
    id: "intel-analytics",
    path: "analytics",
    title: "Intelligence Analytics",
    icon: "analytics",
    filename: "3d0aaca3b7cb46f0adb41b2516f2ec68_SafeNet AI _ Intelligence Analytics.html",
    description: "Statistical reports, trend projections, and performance analysis of AI defensive layers.",
    section: "Intelligence",
  },
  {
    id: "network-graph",
    path: "fraud-network",
    title: "Fraud Network Graph",
    icon: "hub",
    filename: "a202f4ad6c844a1f9f5a331df997f343_SafeNet AI _ Fraud Network Graph.html",
    description: "Node-link visualization showing bank accounts, IP addresses, and phone numbers related to scams.",
    section: "Intelligence",
  },
];

// ── Super Admin Portal Screens ──────────────────────────────
export const adminScreens = [
  {
    id: "executive-dashboard",
    path: "dashboard",
    title: "Executive Dashboard",
    icon: "query_stats",
    filename: "5bb143a217ac408f9cacaa2cb55e7e92_SafeNet AI _ Executive Command Center _Audited_.html",
    description: "High-level visual summary of national incident resolution rates and service availability.",
    section: "Executive",
  },
  {
    id: "officer-management",
    path: "officers",
    title: "Officer Management",
    icon: "badge",
    filename: "4a1666b2ac774037a262412fa33c515c_SafeNet AI _ Officer Management.html",
    description: "Directory and assignment dashboard to coordinate cyber crime officers and response units.",
    section: "Personnel",
  },
  {
    id: "investigation-reports",
    path: "reports",
    title: "Investigation Reports",
    icon: "description",
    filename: "39dfcaaf71e94d7ebafe842dbf682ef2_SafeNet AI _ Investigation Reports.html",
    description: "Case file system containing transcripts, AI summaries, and evidence for active prosecutions.",
    section: "Intelligence",
  },
  {
    id: "evidence-management",
    path: "evidence",
    title: "Evidence Management",
    icon: "folder_zip",
    filename: "34c71ad8b7df4169b2bb223860d7178c_SafeNet AI _ Evidence Management.html",
    description: "Secure archive storing digital forensic details, transaction hashes, and metadata.",
    section: "Intelligence",
  },
  {
    id: "crime-heatmap",
    path: "heatmap",
    title: "Crime Heatmap",
    icon: "map",
    filename: "186710cf74d44c628ee9dda4c6ef7f28_SafeNet AI _ Crime Heatmap Intelligence.html",
    description: "Geospatial visualization of cyber incidents, victim distribution, and hot spot trends.",
    section: "Intelligence",
  },
  {
    id: "intel-analytics",
    path: "analytics",
    title: "Intelligence Analytics",
    icon: "analytics",
    filename: "3d0aaca3b7cb46f0adb41b2516f2ec68_SafeNet AI _ Intelligence Analytics.html",
    description: "Statistical reports, trend projections, and performance analysis of AI defensive layers.",
    section: "Intelligence",
  },
  {
    id: "network-graph",
    path: "fraud-network",
    title: "Fraud Network Graph",
    icon: "hub",
    filename: "a202f4ad6c844a1f9f5a331df997f343_SafeNet AI _ Fraud Network Graph.html",
    description: "Node-link visualization showing bank accounts, IP addresses, and phone numbers related to scams.",
    section: "Intelligence",
  },
  {
    id: "security-control",
    path: "security",
    title: "Security & Access Control",
    icon: "vpn_key",
    filename: "67e56554c78d44bb9b789f852b9644dd_SafeNet AI _ Security _ Access Control.html",
    description: "Manage role-based access control (RBAC), multi-factor tokens, and audit login trails.",
    section: "Platform",
  },
  {
    id: "model-management",
    path: "ai-models",
    title: "AI Model Management",
    icon: "memory",
    filename: "2120f8564564422e878533ff6858d5e8_SafeNet AI _ AI Model Management.html",
    description: "Monitor status, latency, accuracy, and deploy fine-tuned models for spoofing detection.",
    section: "Platform",
  },
  {
    id: "api-integrations",
    path: "api",
    title: "API & Integrations",
    icon: "integration_instructions",
    filename: "722956a7a3a0468d9a390ec66b9c2064_SafeNet AI _ API _ Integrations.html",
    description: "Developer sandbox, webhook configuration, and API reference documentation.",
    section: "Platform",
  },
  {
    id: "infra-management",
    path: "infrastructure",
    title: "Infrastructure & DB",
    icon: "dns",
    filename: "09cdf655873d476681f1fb488e52ff01_SafeNet AI _ Infrastructure _ Database Management.html",
    description: "System diagnostics, server resources, database replication, and query performance metrics.",
    section: "System",
  },
];

// ── Landing / Public Screens ────────────────────────────────
export const landingScreen = {
  id: "landing",
  title: "SafeNet AI Landing Page",
  filename: "9cfd1940762d408d979ffd948e839782_SafeNet AI _ Landing Page.html",
  description: "Public landing page detailing features, security architecture, and public safety integrations.",
};

export const portalScreen = {
  id: "portal",
  title: "Intelligence Platform Home",
  filename: "ae1d4cf9d99b4e10a4e2a473bbcfee38_SafeNet AI Intelligence Platform.html",
  description: "The main portal and gateway for the SafeNet AI Digital Public Safety Intelligence Platform.",
};
