// ─────────────────────────────────────────────────────────────
// Screen Configuration — Role-Separated Exports
// Fully aligned with the required architecture.
// ─────────────────────────────────────────────────────────────

// ── Citizen Portal Screens ──────────────────────────────────
export const citizenScreens = [
  {
    id: "dashboard",
    path: "dashboard",
    title: "Dashboard",
    icon: "dashboard",
    filename: "2b2e31a552f347ffb338c830cd101922_SafeNet AI _ Citizen Dashboard.html",
    description: "Personal portal for citizens to view alerts, file reports, and track investigation updates.",
    section: "Overview",
  },
  {
    id: "fraud-shield",
    path: "fraud-shield",
    title: "AI Fraud Shield",
    icon: "shield_person",
    filename: "3bd34a1afb614ee1855614a2ad682fa1_SafeNet AI _ Citizen Fraud Shield.html",
    description: "AI assistant interface for citizens to verify suspicious links, numbers, and report threats.",
    section: "Tools",
  },
  {
    id: "currency-detector",
    path: "currency-detector",
    title: "Currency Detector",
    icon: "payments",
    filename: "24ba6e2d102649269f47ee4a6c4b427f_SafeNet AI _ Currency Detector.html",
    description: "Computer vision toolkit to verify bank note denominations, watermarks, and security threads.",
    section: "Tools",
  },
  {
    id: "scam-call-analyzer",
    path: "scam-call-analyzer",
    title: "Scam Call Analyzer",
    icon: "settings_phone",
    filename: "15c313655a704125bcc4528018789510_SafeNet AI _ Scam Call Analyzer.html",
    description: "Interactive voice and transcript analysis to verify call legitimacy and detect caller spoofing.",
    section: "Tools",
  },
  {
    id: "my-complaints",
    path: "my-complaints",
    title: "My Complaints",
    icon: "assignment_late",
    filename: "19115426d87249b5a10beba438504720_SafeNet AI _ My Complaints.html",
    description: "Filing and tracking platform for fraud complaints submitted by citizens to law enforcement.",
    section: "My Activity",
  },
  {
    id: "awareness-center",
    path: "awareness-center",
    title: "Awareness Center",
    icon: "campaign",
    filename: "0b775d6a3d5846319b67a1d1e99bd3da_SafeNet AI _ Awareness Center.html",
    description: "Public hub featuring security advisories, scam alert live feed, and educational resources.",
    section: "Resources",
  },
  {
    id: "notifications",
    path: "notifications",
    title: "Notifications",
    icon: "notifications",
    isMock: true,
    mockType: "notifications",
    description: "Updates on filed complaints, threat warnings, and safety broadcasts.",
    section: "System",
  },
  {
    id: "profile",
    path: "profile",
    title: "Profile",
    icon: "person",
    isMock: true,
    mockType: "profile",
    description: "Manage your personal profile, credentials, and digital safety passport.",
    section: "System",
  },
  {
    id: "settings",
    path: "settings",
    title: "Settings",
    icon: "settings",
    isMock: true,
    mockType: "settings",
    description: "Manage threat alert preferences, MFA configurations, and data permissions.",
    section: "System",
  },
];

// ── Officer / Law Enforcement Portal Screens ────────────────
export const officerScreens = [
  {
    id: "dashboard",
    path: "dashboard",
    title: "Dashboard",
    icon: "dashboard",
    filename: "80abb45a24d14286bc80647e693b5b01_SafeNet AI _ Command Center.html",
    description: "Active threat room interface displaying real-time incidents, alerts, and dispatch controls.",
    section: "Overview",
  },
  {
    id: "complaint-management",
    path: "complaints",
    title: "Complaint Management",
    icon: "assignment",
    filename: "19115426d87249b5a10beba438504720_SafeNet AI _ My Complaints.html",
    description: "Manage citizen complaints, verify threat coordinates, and route to local squads.",
    section: "Operations",
  },
  {
    id: "case-management",
    path: "cases",
    title: "Case Management",
    icon: "gavel",
    filename: "39dfcaaf71e94d7ebafe842dbf682ef2_SafeNet AI _ Investigation Reports.html",
    description: "Coordinate pending cyber prosecutions, suspect profiles, and court filings.",
    section: "Operations",
  },
  {
    id: "citizen-reports",
    path: "citizen-reports",
    title: "Citizen Reports",
    icon: "feed",
    filename: "19115426d87249b5a10beba438504720_SafeNet AI _ My Complaints.html",
    description: "Review incoming public complaints, scam phone numbers, and phishing URLs.",
    section: "Operations",
  },
  {
    id: "fraud-shield-cases",
    path: "fraud-shield-cases",
    title: "Fraud Shield Cases",
    icon: "shield",
    filename: "3bd34a1afb614ee1855614a2ad682fa1_SafeNet AI _ Citizen Fraud Shield.html",
    description: "Administer high-confidence fraud reports from citizen AI assistant scans.",
    section: "Operations",
  },
  {
    id: "counterfeit-intel",
    path: "counterfeit-intel",
    title: "Counterfeit Intelligence",
    icon: "currency_rupee",
    filename: "24ba6e2d102649269f47ee4a6c4b427f_SafeNet AI _ Currency Detector.html",
    description: "Analyze submitted currency notes for intaglio ink, watermarks, and counterfeit indicators.",
    section: "Intelligence",
  },
  {
    id: "scam-call-intel",
    path: "scam-call-intel",
    title: "Scam Call Intelligence",
    icon: "call",
    filename: "15c313655a704125bcc4528018789510_SafeNet AI _ Scam Call Analyzer.html",
    description: "Review voice transcripts and spoofing risk metrics submitted by citizens.",
    section: "Intelligence",
  },
  {
    id: "fraud-network",
    path: "fraud-network",
    title: "Fraud Network",
    icon: "hub",
    filename: "a202f4ad6c844a1f9f5a331df997f343_SafeNet AI _ Fraud Network Graph.html",
    description: "Node-link visualization showing bank accounts, IP addresses, and phone numbers related to scams.",
    section: "Intelligence",
  },
  {
    id: "crime-heatmap",
    path: "heatmap",
    title: "Crime Heatmap",
    icon: "map",
    filename: "186710cf74d44c628ee9dda4c6ef7f28_SafeNet AI _ Crime Heatmap Intelligence.html",
    description: "Geospatial visualization of cyber incidents, victim distribution, and hot spot trends.",
    section: "Intelligence",
  },
  {
    id: "analytics",
    path: "analytics",
    title: "Analytics",
    icon: "analytics",
    filename: "3d0aaca3b7cb46f0adb41b2516f2ec68_SafeNet AI _ Intelligence Analytics.html",
    description: "Statistical reports, trend projections, and performance analysis of AI defensive layers.",
    section: "Intelligence",
  },
  {
    id: "evidence",
    path: "evidence",
    title: "Evidence",
    icon: "folder_zip",
    filename: "34c71ad8b7df4169b2bb223860d7178c_SafeNet AI _ Evidence Management.html",
    description: "Secure archive storing digital forensic details, transaction hashes, and metadata.",
    section: "Operations",
  },
  {
    id: "reports",
    path: "reports",
    title: "Reports",
    icon: "description",
    filename: "39dfcaaf71e94d7ebafe842dbf682ef2_SafeNet AI _ Investigation Reports.html",
    description: "Case file system containing transcripts, AI summaries, and evidence for active prosecutions.",
    section: "Operations",
  },
  {
    id: "alerts",
    path: "alerts",
    title: "Alerts",
    icon: "campaign",
    filename: "0b775d6a3d5846319b67a1d1e99bd3da_SafeNet AI _ Awareness Center.html",
    description: "Publish security alerts, advisory briefings, and regional emergency advisories.",
    section: "Resources",
  },
  {
    id: "officer-profile",
    path: "profile",
    title: "Officer Profile",
    icon: "badge",
    isMock: true,
    mockType: "profile",
    description: "Officer details, badge number, station assignment, and operational clearance level.",
    section: "System",
  },
  {
    id: "settings",
    path: "settings",
    title: "Settings",
    icon: "settings",
    isMock: true,
    mockType: "settings",
    description: "Configure notification dispatch hooks, active watch zones, and system overrides.",
    section: "System",
  },
];

// ── Super Admin Portal Screens ──────────────────────────────
export const adminScreens = [
  {
    id: "executive-dashboard",
    path: "dashboard",
    title: "Executive Dashboard",
    icon: "query_stats",
    filename: "5bb143a217ac408f9cacaa2cb55e7e92_SafeNet AI _ Executive Command Center _Audited_.html",
    description: "High-level visual summary of national incident resolution rates and service availability.",
    section: "Executive",
  },
  {
    id: "user-management",
    path: "users",
    title: "User Management",
    icon: "manage_accounts",
    filename: "4a1666b2ac774037a262412fa33c515c_SafeNet AI _ Officer Management.html",
    description: "Manage global platform accounts, citizen access logs, and account activation workflows.",
    section: "Personnel",
  },
  {
    id: "officer-management",
    path: "officers",
    title: "Officer Management",
    icon: "badge",
    filename: "4a1666b2ac774037a262412fa33c515c_SafeNet AI _ Officer Management.html",
    description: "Directory and assignment dashboard to coordinate cyber crime officers and response units.",
    section: "Personnel",
  },
  {
    id: "roles",
    path: "roles",
    title: "Roles",
    icon: "admin_panel_settings",
    filename: "67e56554c78d44bb9b789f852b9644dd_SafeNet AI _ Security _ Access Control.html",
    description: "Configure role-based access controls, node access thresholds, and profile keys.",
    section: "Personnel",
  },
  {
    id: "departments",
    path: "departments",
    title: "Departments",
    icon: "corporate_fare",
    filename: "4a1666b2ac774037a262412fa33c515c_SafeNet AI _ Officer Management.html",
    description: "Manage organizational structures, regional cyber units, and dispatch routing.",
    section: "Personnel",
  },
  {
    id: "ai-models",
    path: "ai-models",
    title: "AI Models",
    icon: "memory",
    filename: "2120f8564564422e878533ff6858d5e8_SafeNet AI _ AI Model Management.html",
    description: "Monitor status, latency, accuracy, and deploy fine-tuned models for spoofing detection.",
    section: "Platform",
  },
  {
    id: "api-management",
    path: "api",
    title: "API Management",
    icon: "integration_instructions",
    filename: "722956a7a3a0468d9a390ec66b9c2064_SafeNet AI _ API _ Integrations.html",
    description: "Developer sandbox, webhook configuration, and API reference documentation.",
    section: "Platform",
  },
  {
    id: "infrastructure",
    path: "infrastructure",
    title: "Infrastructure",
    icon: "dns",
    filename: "09cdf655873d476681f1fb488e52ff01_SafeNet AI _ Infrastructure _ Database Management.html",
    description: "System diagnostics, server resources, database replication, and query performance metrics.",
    section: "System",
  },
  {
    id: "database",
    path: "database",
    title: "Database",
    icon: "database",
    filename: "09cdf655873d476681f1fb488e52ff01_SafeNet AI _ Infrastructure _ Database Management.html",
    description: "Database diagnostics, query logs, replication offsets, and storage partitions.",
    section: "System",
  },
  {
    id: "security-center",
    path: "security",
    title: "Security Center",
    icon: "vpn_key",
    filename: "67e56554c78d44bb9b789f852b9644dd_SafeNet AI _ Security _ Access Control.html",
    description: "Manage global portal security, firewalls, and cryptographic session properties.",
    section: "System",
  },
  {
    id: "audit-logs",
    path: "audit-logs",
    title: "Audit Logs",
    icon: "receipt_long",
    filename: "67e56554c78d44bb9b789f852b9644dd_SafeNet AI _ Security _ Access Control.html",
    description: "Tamper-proof audit trail tracking administrative queries and login checkpoints.",
    section: "System",
  },
  {
    id: "reports",
    path: "reports",
    title: "Reports",
    icon: "description",
    filename: "39dfcaaf71e94d7ebafe842dbf682ef2_SafeNet AI _ Investigation Reports.html",
    description: "View aggregate incident dossiers and compiled prosecution filings.",
    section: "Intelligence",
  },
  {
    id: "analytics",
    path: "analytics",
    title: "Analytics",
    icon: "analytics",
    filename: "3d0aaca3b7cb46f0adb41b2516f2ec68_SafeNet AI _ Intelligence Analytics.html",
    description: "Review global analytical trends, regional incidents, and system defense efficacy.",
    section: "Intelligence",
  },
  {
    id: "admin-profile",
    path: "profile",
    title: "Admin Profile",
    icon: "person",
    isMock: true,
    mockType: "profile",
    description: "Manage admin profile details and system access credentials.",
    section: "System",
  },
  {
    id: "settings",
    path: "settings",
    title: "Settings",
    icon: "settings",
    isMock: true,
    mockType: "settings",
    description: "Configure system variables, gateway API keys, and maintenance windows.",
    section: "System",
  },
];

// ── Landing / Public Screens ────────────────────────────────
export const landingScreen = {
  id: "landing",
  title: "SafeNet AI Landing Page",
  filename: "9cfd1940762d408d979ffd948e839782_SafeNet AI _ Landing Page.html",
  description: "Public landing page detailing features, security architecture, and public safety integrations.",
};

export const portalScreen = {
  id: "portal",
  title: "Intelligence Platform Home",
  filename: "ae1d4cf9d99b4e10a4e2a473bbcfee38_SafeNet AI Intelligence Platform.html",
  description: "The main portal and gateway for the SafeNet AI Digital Public Safety Intelligence Platform.",
};
